################################# Default configuration ###################
# baseURL = "https://сайткомп.рф"
baseURL = "https://saytkomp.github.io"
title = "СайтКомп Разработка и создание сайтов"
theme = "meghna"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = "en"

DefaultContentLanguage = "ru"


############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/animate-css/animate.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/wow/wow.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################# Navigation ##################################
[[menu.main]]
name = "Обо Мне"
URL = "about"
weight = 1

[[menu.main]]
name = "Услуги"
URL = "services"
weight = 2

[[menu.main]]
name = "Мои Работы"
URL = "portfolio"
weight = 3

[[menu.main]]
name = "Цены"
URL = "pricing"
weight = 4

# [[menu.main]]
# name = "Заметки"
# URL = "blog"
# weight = 5

[[menu.main]]
name = "Контакты"
URL = "contact"
weight = 6



############################# Default Parameters ##########################
[params]
logo = "images/logo.svg"
# Meta data
description = "СайтКомп.рф занимается разработкой качественных и уникальных сайтов. Быстрое выполнение, недорогая стоимость разработки сайта, индивидуальное изготовление по требованиям заказчика. Разработка сайта под ключ цена в Москве."
author = "СайтКомп"
# Google Analitycs
google_analitycs_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = true
preloader = "images/logo.svg"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"

################################ France Language ########################
[Languages.ru]
languageName = "Ru"
languageCode = "ru-Ru"
contentDir = "content/russian"
weight = 1
home = "Главная"